### ISSUE TITLE
Link to Trending Videos is 404 ... :-(

### ISSUE THREAD

**Issue by nelsonic** [markwilliamfirth/markwilliamfirth.github.io#1]
On your page > **Internet & Pop Culture** you link to:
https://www.youtube.com/playlist?list=FLeNZlh03MyUkjRlLFpVQxsg!

<img width="925" alt="link-fail" src="https://cloud.githubusercontent.com/assets/194400/9861892/2a548078-5b2d-11e5-9156-5260b0142863.png">

**Comment by markwilliamfirth** [comment]
Fixed :)
